### ISSUE TITLE
cudnn.SpatialDilatedConvolution

### ISSUE THREAD

**Issue by musicrainie** [fqnchina/ImageSmoothing#2]
When run "th ./test_smooth.lua", I got the following error "...age_Smoothing/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <cudnn.SpatialDilatedConvolution>", which occurred in the line https://github.com/fqnchina/ImageSmoothing/blob/efacee362bb6e4da0bc8d02bdcffda55a68c2a5a/test_smooth.lua#L27

In my installation, the 'SpatialDilatedConvolution' can be found in "./torch/extra/nn/init.lua" but not in "./torch/extra/cudnn/init.lua", which makes me think this cudnn version of SpatialDilatedConvolution is your implementation. Is that the case?

My setting is Ubuntu16.04, torch7, cuda-8.0 and cudnn-6.0, and I have succeeded in compiling all the files under the "/compilation" folder according to your instructions.

Any help would be appreciated.

**Comment by fqnchina** [comment]
Hi,

The problem lies in incompatible version of CUDNN. Probably in cudnn-6.0, this function is not implemented. I will suggest to update the cudnn version and compile its corresponding module in ./torch/extra/cudnn/. 

To install the corresponding cudnn module, you can download it from https://github.com/soumith/cudnn.torch, run "git checkout R*", and compile it again.

Thanks,

**Comment by musicrainie** [comment]
As you said, cudnn6 was updated to version7 and the test passed. Thanks very much. Gorgeous work and amazing results, btw.

**Comment by sameerkumar358** [comment]
@musicrainie does Ubuntu16.04, torch7, cuda-8.0 and cudnn-7.0 worked in your case??
